// List of verses displayed on the block page
// Kept as a global variable for use in script.js
window.motivationalQuotes = [
  'Ephesians 2:8-9 — "For by grace you have been saved through faith, and this is not from yourselves, it is the gift of God; not by works, so that no one can boast."',
  'John 3:16 — "For God so loved the world that He gave His one and only Son, that whoever believes in Him shall not perish but have eternal life."',
  'Romans 3:23-24 — "For all have sinned and fall short of the glory of God, and all are justified freely by His grace through the redemption that is in Christ Jesus."',
  'Romans 6:23 — "For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord."',
  'Romans 5:8 — "But God demonstrates His own love for us in this: while we were still sinners, Christ died for us."',
  'Romans 10:9-10 — "If you confess with your mouth, ‘Jesus is Lord,’ and believe in your heart that God raised Him from the dead, you will be saved. For with the heart one believes and is justified, and with the mouth one confesses and is saved."',
  'Acts 4:12 — "Salvation is found in no one else, for there is no other name under heaven given to mankind by which we must be saved."',
  '2 Corinthians 5:17 — "Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come!"',
  '2 Corinthians 5:21 — "God made Him who had no sin to be sin for us, so that in Him we might become the righteousness of God."',
  '1 John 5:11-12 — "And this is the testimony: God has given us eternal life, and this life is in His Son. Whoever has the Son has life; whoever does not have the Son of God does not have life."',
  'John 14:6 — "I am the way and the truth and the life. No one comes to the Father except through Me."',
  'John 1:12 — "Yet to all who received Him, to those who believed in His name, He gave the right to become children of God."',
  'Revelation 3:20 — "Behold, I stand at the door and knock. If anyone hears My voice and opens the door, I will come in and dine with him, and he with Me."',
  'Matthew 11:28-30 — "Come to Me, all who are weary and burdened, and I will give you rest…"',
  'Luke 19:10 — "For the Son of Man came to seek and to save the lost."',
  'Mark 1:15 — "The time is fulfilled, and the kingdom of God is at hand; repent and believe in the gospel."',
  'Acts 3:19 — "Repent therefore, and turn back, that your sins may be blotted out."',
  'Acts 16:31 — "Believe in the Lord Jesus, and you will be saved—you and your household."',
  '1 Peter 3:18 — "For Christ also suffered once for sins, the righteous for the unrighteous, that He might bring us to God."',
  'Romans 8:1 — "Therefore, there is now no condemnation for those who are in Christ Jesus."',
  'Galatians 2:20 — "I have been crucified with Christ and I no longer live, but Christ lives in me…"',
  'Galatians 3:13 — "Christ redeemed us from the curse of the law by becoming a curse for us."',
  'Colossians 1:13-14 — "He has delivered us from the domain of darkness and transferred us to the kingdom of His beloved Son, in whom we have redemption, the forgiveness of sins."',
  'Hebrews 7:25 — "Therefore He is able to save completely those who come to God through Him, because He always lives to intercede for them."',
  'Hebrews 9:27-28 — "… so Christ was sacrificed once to take away the sins of many; and He will appear a second time…"',
  '1 Timothy 2:5-6 — "For there is one God and one Mediator between God and mankind, the man Christ Jesus, who gave Himself as a ransom for all."',
  '1 Timothy 1:15 — "Here is a trustworthy saying that deserves full acceptance: Christ Jesus came into the world to save sinners."',
  'James 4:8 — "Draw near to God and He will draw near to you…"',
  '1 John 1:9 — "If we confess our sins, He is faithful and just and will forgive us our sins and purify us from all unrighteousness."',
  'John 11:25-26 — "I am the resurrection and the life. The one who believes in Me will live, even though they die."',
  'John 20:31 — "…that you may believe that Jesus is the Christ, the Son of God, and that by believing you may have life in His name."',
  'John 6:35 — "I am the bread of life. Whoever comes to Me shall not hunger, and whoever believes in Me shall never thirst."',
  'John 10:9-11 — "I am the door. If anyone enters by Me, he will be saved… I am the good shepherd. The good shepherd lays down His life for the sheep."',
  'John 8:12 — "I am the light of the world. Whoever follows Me will never walk in darkness, but will have the light of life."',
  'John 7:38 — "Whoever believes in Me, as Scripture has said, rivers of living water will flow from within them."',
  'John 17:3 — "Now this is eternal life: that they know You, the only true God, and Jesus Christ, whom You have sent."',
  'Romans 1:16 — "For I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes."',
  'Romans 10:13 — "For everyone who calls on the name of the Lord will be saved."',
  '2 Corinthians 6:2 — "Behold, now is the favorable time; behold, now is the day of salvation."',
  'Psalm 51:10 — "Create in me a clean heart, O God, and renew a steadfast spirit within me."',
  'Isaiah 53:5-6 — "… the punishment that brought us peace was on Him, and by His wounds we are healed."',
  'Isaiah 55:6-7 — "Seek the Lord while He may be found; call on Him while He is near."',
  'Jeremiah 29:13 — "You will seek Me and find Me when you seek Me with all your heart."',
  'Psalm 32:1-2 — "Blessed is the one whose transgressions are forgiven, whose sins are covered."',
  'Psalm 34:8 — "Taste and see that the Lord is good; blessed is the one who takes refuge in Him."',
  'Proverbs 3:5-6 — "Trust in the Lord with all your heart and lean not on your own understanding…"',
  'Isaiah 1:18 — "Come now, let us settle the matter, says the Lord. Though your sins are like scarlet, they shall be as white as snow."',
  'Isaiah 43:25 — "I, even I, am He who blots out your transgressions, for My own sake…"',
  'Isaiah 45:22 — "Turn to Me and be saved, all you ends of the earth; for I am God, and there is no other."',
  'Zephaniah 3:17 — "The Lord your God is with you, the Mighty Warrior who saves…"',
  'Zechariah 1:3 — "Return to Me, says the Lord of Hosts, and I will return to you."',
  'Micah 7:18-19 — "Who is a God like You, who pardons iniquity… and You will cast all their sins into the depths of the sea."',
  'Jonah 2:9 — "Salvation belongs to the Lord."',
  'Matthew 1:21 — "He will save His people from their sins."',
  'Matthew 4:17 — "Repent, for the kingdom of heaven is near."',
  'Matthew 5:16 — "Let your light shine before others, so that they may see your good works and give glory to your Father in heaven."',
  'Matthew 6:33 — "But seek first His kingdom and His righteousness…"',
  'Matthew 7:7-8 — "Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you."',
  'Matthew 9:13 — "I desire mercy and not sacrifice. For I came not to call the righteous, but sinners."',
  'Matthew 20:28 — "…the Son of Man did not come to be served, but to serve, and to give His life as a ransom for many."',
  'Matthew 28:19-20 — "Go therefore and make disciples of all nations…"',
  'Mark 8:34-35 — "If anyone would come after Me, let him deny himself, take up his cross, and follow Me."',
  'Mark 10:45 — "For even the Son of Man came not to be served but to serve, and to give His life as a ransom for many."',
  'Luke 5:31-32 — "Those who are well have no need of a physician, but those who are sick. I have not come to call the righteous but sinners to repentance."',
  'Luke 13:3 — "…unless you repent, you will all likewise perish."',
  'Luke 23:43 — "Truly I tell you, today you will be with Me in paradise."',
  'Acts 1:8 — "But you will receive power when the Holy Spirit has come upon you, and you will be My witnesses…"',
  'Acts 2:21 — "And everyone who calls on the name of the Lord will be saved."',
  'Acts 2:38 — "Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of your sins."',
  'Acts 10:43 — "All the prophets testify about Him that everyone who believes in Him receives forgiveness of sins through His name."',
  'Acts 13:38-39 — "…through Him forgiveness of sins is proclaimed to you."',
  'Acts 17:30-31 — "God now commands all people everywhere to repent…"',
  '1 Corinthians 1:18 — "The message of the cross is foolishness to those who are perishing, but to us who are being saved it is the power of God."',
  '1 Corinthians 6:19-20 — "…you were bought at a price. Therefore glorify God with your body."',
  '1 Corinthians 15:3-4 — "Christ died for our sins according to the Scriptures, was buried and was raised on the third day."',
  '2 Corinthians 4:6 — "For God, who said, ‘Let light shine out of darkness,’ made His light shine in our hearts…"',
  '2 Corinthians 5:14-15 — "…He died for all, that those who live should no longer live for themselves…"',
  '2 Corinthians 5:19-20 — "God was reconciling the world to Himself in Christ… We are therefore Christ’s ambassadors, as though God were making His appeal through us."',
  'Galatians 3:26 — "So in Christ Jesus you are all children of God through faith."',
  'Galatians 6:14 — "May I never boast except in the cross of our Lord Jesus Christ."',
  'Ephesians 1:7 — "In Him we have redemption through His blood, the forgiveness of sins, in accordance with the riches of His grace."',
  'Ephesians 2:4-5 — "But God, being rich in mercy, because of His great love… made us alive together with Christ."',
  'Ephesians 3:12 — "In Him and through faith in Him we may approach God with freedom and confidence."',
  'Philippians 3:8-9 — "…that I may gain Christ and be found in Him, not having a righteousness of my own that comes from the law, but that which is through faith in Christ."',
  'Colossians 2:13-14 — "God made you alive with Christ. He forgave us all our sins, having canceled the charge of our legal indebtedness…"',
  '1 Thessalonians 5:9-10 — "For God did not appoint us to suffer wrath but to receive salvation through our Lord Jesus Christ."',
  '2 Thessalonians 2:13-14 — "God chose you as firstfruits to be saved through the sanctifying work of the Spirit and through belief in the truth."',
  'Titus 2:11 — "For the grace of God has appeared that offers salvation to all people."',
  'Titus 3:4-7 — "…He saved us, not because of righteous things we had done, but because of His mercy. He saved us through the washing of rebirth and renewal by the Holy Spirit."',
  'Hebrews 4:16 — "Let us then approach God’s throne of grace with confidence, so that we may receive mercy…"',
  'Hebrews 10:10 — "By that will, we have been made holy through the sacrifice of the body of Jesus Christ once for all."',
  'Hebrews 12:2 — "Fixing our eyes on Jesus, the author and perfecter of faith…"',
  'Hebrews 12:28 — "…let us be thankful, and so worship God acceptably with reverence and awe."',
  '1 Peter 1:18-19 — "…you were redeemed with the precious blood of Christ, a lamb without blemish or defect."',
  '1 Peter 2:24 — "He Himself bore our sins in His body on the cross…"',
  '1 Peter 5:10 — "The God of all grace, who called you to His eternal glory in Christ… will Himself restore you."',
  '2 Peter 3:9 — "The Lord is not slow in keeping His promise… but is patient with you, not wanting anyone to perish."',
  '1 John 2:1-2 — "We have an Advocate with the Father—Jesus Christ, the Righteous One. He is the atoning sacrifice for our sins."',
  '1 John 4:9-10 — "This is how God showed His love among us: He sent His one and only Son into the world…"',
  'Jude 1:24-25 — "To Him who is able to keep you from stumbling and to present you before His glorious presence without fault…"',
  'Revelation 1:5 — "To Him who loves us and has freed us from our sins by His blood…"',
  'Revelation 5:9 — "…because You were slain, and with Your blood You purchased for God persons from every tribe and language and people and nation."',
  'Revelation 21:6 — "I am the Alpha and the Omega… To the thirsty I will give water without cost from the spring of the water of life."',
  'Revelation 22:17 — "The Spirit and the bride say, ‘Come!’… Let the one who is thirsty come; and let the one who wishes take the free gift of the water of life."',
  'Acts 3:19 — "Repent, then, and turn to God, so that your sins may be wiped out."',
  'Luke 5:32 — "I have not come to call the righteous, but sinners to repentance."',
  '2 Chronicles 7:14 — "If My people… will humble themselves and pray and seek My face and turn from their wicked ways…"',
  'Proverbs 28:13 — "Whoever conceals their sins does not prosper, but the one who confesses and renounces them finds mercy."',
  'Mark 1:15 — "The time has come… The kingdom of God has come near. Repent and believe the good news!"',
  'Joel 2:13 — "Rend your heart and not your garments. Return to the Lord your God, for He is gracious and compassionate."',
  'Isaiah 55:7 — "Let the wicked forsake their ways… and turn to the Lord, and He will have mercy on them."',
  'Matthew 4:17 — "Repent, for the kingdom of heaven has come near."',
  'Ezekiel 18:30 — "Repent! Turn away from all your offenses; then sin will not be your downfall."',
  'Psalm 51:17 — "A broken and contrite heart You, God, will not despise."',
  'Acts 17:30 — "God now commands all people everywhere to repent."',
  'Revelation 3:19 — "Those whom I love I rebuke and discipline. So be earnest and repent."',
  'Matthew 3:8 — "Produce fruit in keeping with repentance."',
  'Romans 2:4 — "God’s kindness is intended to lead you to repentance."',
  'James 4:8-9 — "Wash your hands, you sinners… Grieve, mourn and wail. Change your laughter to mourning and your joy to gloom."',
  'Hosea 6:1 — "Come, let us return to the Lord. He has torn us to pieces but He will heal us."',
  'Luke 24:47 — "Repentance for the forgiveness of sins will be preached in His name to all nations."',
  'Proverbs 3:5-6 — "Trust in the Lord with all your heart and lean not on your own understanding…"',
  'Psalm 37:5 — "Commit your way to the Lord; trust in Him and He will do this."',
  'Isaiah 26:3 — "You will keep in perfect peace those whose minds are steadfast, because they trust in You."',
  'Psalm 56:3 — "When I am afraid, I put my trust in You."',
  'Jeremiah 17:7 — "Blessed is the one who trusts in the Lord, whose confidence is in Him."',
  'Psalm 9:10 — "Those who know Your name trust in You, for You, Lord, have never forsaken those who seek You."',
  'Psalm 28:7 — "The Lord is my strength and my shield; my heart trusts in Him, and He helps me."',
  'Psalm 62:8 — "Trust in Him at all times, you people; pour out your hearts to Him, for God is our refuge."',
  'Psalm 91:2 — "I will say of the Lord, ‘He is my refuge and my fortress, my God, in whom I trust.’"',
  'Nahum 1:7 — "The Lord is good, a refuge in times of trouble. He cares for those who trust in Him."',
  '2 Samuel 22:31 — "As for God, His way is perfect… He shields all who take refuge in Him."',
  'Psalm 112:7 — "They will have no fear of bad news; their hearts are steadfast, trusting in the Lord."',
  'Isaiah 12:2 — "Surely God is my salvation; I will trust and not be afraid."',
  'Hebrews 13:5-6 — "The Lord is my helper; I will not be afraid. What can mere mortals do to me?"',
  'Romans 15:13 — "May the God of hope fill you with all joy and peace as you trust in Him."',
  'Psalm 20:7 — "Some trust in chariots and some in horses, but we trust in the name of the Lord our God."',
  'John 14:1 — "Do not let your hearts be troubled. You believe in God; believe also in Me."',
  'John 14:15 — "If you love Me, keep My commands."',
  '1 Samuel 15:22 — "To obey is better than sacrifice."',
  'James 1:22 — "Do not merely listen to the word… Do what it says."',
  'Deuteronomy 5:33 — "Walk in obedience to all that the Lord your God has commanded you…"',
  'Luke 11:28 — "Blessed rather are those who hear the word of God and obey it."',
  'Deuteronomy 28:1 — "If you fully obey the Lord your God… all these blessings will come on you."',
  'Matthew 7:24 — "Everyone who hears these words of Mine and puts them into practice is like a wise man…"',
  'Hebrews 5:9 — "He became the source of eternal salvation for all who obey Him."',
  'John 15:10 — "If you keep My commands, you will remain in My love."',
  'Joshua 1:8 — "Do not let this Book of the Law depart from your mouth… Be careful to do everything written in it."',
  '1 John 2:3 — "We know that we have come to know Him if we keep His commands."',
  '2 John 1:6 — "And this is love: that we walk in obedience to His commands."',
  'Romans 6:16 — "You are slaves of the one you obey… whether of sin or of obedience leading to righteousness."',
  'Acts 5:29 — "We must obey God rather than men."',
  'Psalm 119:60 — "I will hasten and not delay to obey Your commands."',
  'Exodus 19:5 — "If you obey Me fully and keep My covenant, then out of all nations you will be My treasured possession."'
];

